---
title: "LIBRARY TMAP"
author: "Pinedo Cienfuegos, Diana Melissa"
date: "31/1/2022"
output: github_document
---


## TMAP

**Facilita en la realizacion de mapas tematicos, con funciones estetica atributo entre otras**

- Utilizaremos las librerias "tmap" para realizar el mapa tematico y "sf" para el manejo de datos vectoriales

```{r}
library(tmap)
library(sf)
setwd("C:/Users/edgar/Desktop/IV CICLO/MOQUEGUA")
dir()
```

- Lectura del archivo shapefile dentro de R

 moquegua <- st_read("Moquegua.shp")
 moquegua

moquegua

**ALGUNAS DE LAS FUNCIONES UTILIZADAS**

- Para mapa tematico r치pico

tm_shape(moquegua) + tm_polygons()


- Agregando y modificando funciones

 tm_shape(moquegua) + 
   tm_polygons('TAnalfab', style = 'quantile')


- Funci칩n "tm_facets" Sirve para modificar y manipular las diferentes vistas que se dan de los mapas

tm_shape(moquegua) +
  tm_polygons(c("TAnalfab", "Pobreza","salud19","edu_19")) +
  tm_facets(sync = TRUE, ncol = 4)


- Funci칩n "tmap_mode("view")" permite manipular las vistas del mapa de manera din치mica.

tmap_mode("view")

tm_shape(moquegua) +
  tm_polygons(c("TAnalfab", "Pobreza")) +
  tm_facets(sync = TRUE, ncol = 2)


- OpenTopoMap(). 
Stamen.Watercolor

Funciones esteticas
### tm_fill() / tm_borders()

tm_shape(moquegua) +
  tm_fill(col="TAnalfab", style="kmeans")+
  tm_borders("red", alpha=1)  

  
## Con la data "World" y "metro"
### tm_dots() / tm_bubbles() / tm_squares() / tm_markers()
data("World")
data("metro")

tm_shape(World) + tm_polygons("HPI") +
  tm_shape(metro) + tm_dots()

tm_shape(World) + tm_polygons("HPI") +
  tm_shape(metro) + tm_bubbles(size=.2, col="blue")

tm_shape(World) + tm_polygons("HPI") +
  tm_shape(metro) + tm_squares(size=.1, col="blue")
  
tm_shape(World) + tm_polygons("HPI") +
  tm_shape(metro) + tm_markers(size=.08)





